import MainNavbar from "@/src/layout/MainNavbar";
import Sidebar from "@/src/layout/Sidebar";
import { Box, CssBaseline, Paper, SelectChangeEvent, styled, Typography } from "@mui/material";
import DashboardIcon from "@mui/icons-material/Dashboard";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Employee from "@/src/components/dashboard/Employee";

const DashboardPage: NextPage = () => {
    const [open, setOpen] = React.useState(true);
    const [OtNumber, setOtNumber] = React.useState("");
    const handleChange = (event: SelectChangeEvent) => {
        setOtNumber(event.target.value);
    };

    const Main = styled("main", { shouldForwardProp: (prop) => prop !== "open" })<{
        open?: boolean;
    }>(({ theme, open }) => ({
        flexGrow: 1,
        padding: theme.spacing(3),
        transition: theme.transitions.create(["margin", "width"], {
            easing: theme.transitions.easing.sharp,
            duration: theme.transitions.duration.leavingScreen,
        }),
        ...(open && {
            width: !open ? "100%" : "82%",
            marginLeft: "18%",
            position: "relative",
            transition: theme.transitions.create(["margin", "width"], {
                easing: theme.transitions.easing.easeOut,
                duration: theme.transitions.duration.enteringScreen,
            }),
        }),
    }));

    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box sx={{ backgroundColor: "#5B848D", width: "100%", height: "100vh" }}>
                <CssBaseline />
                <MainNavbar isOpen={(status) => setOpen(status)} />
                <Sidebar isOpen={open} />
                <Paper
                    sx={{
                        backgroundColor: "#044453",
                        width: open ? "82%" : "100%",
                        marginLeft: open ? "18%" : null,
                        padding: "7px 10px",
                        display: "flex",
                        flexDirection: "row",
                        gap: 1,
                        paddingLeft: 2.9,
                    }}
                    square
                >
                    <DashboardIcon sx={{ color: "white", margin: "auto 0", fontSize: 35 }} />
                    <Typography color="white" variant="h6" my="auto">
                        Dashboard
                    </Typography>
                </Paper>
            </Box>
        </Box>
    );
};

export default DashboardPage;
