import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import Navbar from "@/src/layout/Navbar";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Box sx={{backgroundColor: "#5B848D", width: "100%", height: "100vh" ,}}></Box>
        </Box>
    );
}
